import { Footer } from "@/components/footer"
import { Menu } from "@/components/menu"
import "../globals.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" >
       
      <body className="h-screen antialiased">
      <Menu op1="Home" op2="Math" op3="General Functions" op4="FetchNativo" op5="AxiosPage" op6="ServerPage"/>
      <div className="flex  h-full flex-wrap gap-4 justify-center items-center my-4">
        {children}
      </div>
      
      </body>

    </html>
  )
}
