import { Footer } from "@/components/footer"
import { Menu } from "@/components/menu"
import "../globals.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" >
       
      <body className="h-screen">{children}</body>

    </html>
  )
}
